# service-example/shell.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - name: shell
        image: alpine
        command:
          - sleep
          - infinity
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
