apiVersion: v1
kind: Pod
metadata:
  name: 2ndpod
  labels:
    name: 2ndpod
spec:
  containers:
  - name: 2ndpod
    image: ubuntu:22.04
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - "/bin/sleep"
      - "infinity"
  - name: 3rdpod
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - "/bin/sleep"
      - "infinity"

