apiVersion: v1
kind: Pod
metadata:
  name: initsample
  labels:
    name: initsample
spec:
  volumes:
    - name: contents
      emptyDir: {}

  containers:
  - name: initsample
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: contents
        readOnly: true
  initContainers:
    - name: init
      image: alpine
      volumeMounts:
        - mountPath: /contents
          name: contents
      command:
        - sh
        - "-c"
        - "date > /contents/index.html"
