apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-check
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: mariadb-check
        image: ubuntu:22.04
        command:
          - bash
          - "-c"
          - "apt-get update; apt-get install -y mariadb-client; mysqladmin ping -u root --password=dbadmin -h mariadb"
      restartPolicy: Never
