apiVersion: v1
kind: Pod
metadata:
  name: mountfile1
  labels:
    name: mountfile1
spec:
  containers:
  - name: mountfile1
    image: alpine
    command:
    - sleep
    - infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /data
        name: data
      - mountPath: /data-all
        name: config
  volumes:
    - name: data
      configMap:
        name: file1
    - name: config
      configMap:
        name: config
