# secret-pod-example.yml
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: alpine
    command:
      - sleep
      - infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /data
        name: data
    env:
      # 環境変数参照の例
      - name: sample
        valueFrom:
          secretKeyRef:
            key: sample
            name: mysecret
  volumes:
    # ボリューム扱いの例
    - name: data
      secret:
        secretName: mysecret
