# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout sources
      uses: actions/checkout@v3
    - name: check current dir
      run: |
        pwd
        ls -al
    # Runs a single command using the runners shell
    - name: setup jupyter book
      run: |
        sudo apt-get update
        sudo LC_ALL=ja_JP.UTF-8 TZ=Asia/Tokyo apt-get install locales
        echo "ja_JP.UTF-8 UTF-8" | sudo tee -a /etc/locales.gen; sudo locale-gen
        sudo apt-get install -y python3.9
        pip3 install jupyter-book markupsafe==2.0.1
    - name: build book
      run: |
        export LC_ALL=ja_JP.UTF-8
        jb build .
